//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace arkivverket.noark5tj.metadata {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Arkivdelstatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class ArkivdelstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Arkivstatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class ArkivstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Avskrivningsmaate", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class AvskrivningsmaateType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Dokumentmedium", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class DokumentmediumType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Dokumentstatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class DokumentstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Dokumenttype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class DokumenttypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("ElektroniskSignaturSikkerhetsnivaa", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class ElektroniskSignaturSikkerhetsnivaaType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("ElektroniskSignaturVerifisert", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class ElektroniskSignaturVerifisertType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("FlytStatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class FlytStatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Format", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class FormatType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Graderingskode", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class GraderingskodeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Hendelsetype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class HendelsetypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Journalposttype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class JournalposttypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Journalstatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class JournalstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Kassasjonsvedtak", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class KassasjonsvedtakType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Klassifikasjonstype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class KlassifikasjonstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Korrespondanseparttype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class KorrespondanseparttypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Land", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class LandType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Mappetype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class MappetypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Merknadstype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class MerknadstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("MoetedeltakerFunksjon", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class MoetedeltakerFunksjonType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Moeteregistreringsstatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class MoeteregistreringsstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Moeteregistreringstype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class MoeteregistreringstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Moetesakstype", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class MoetesakstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Postnummer", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class PostnummerType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Presedensstatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class PresedensstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("ProsessStatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class ProsessStatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("SakspartRolle", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class SakspartRolleType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Saksstatus", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class SaksstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("SkjermingDokument", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class SkjermingDokumentType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("SkjermingMetadata", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class SkjermingMetadataType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Tilgangskategori", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class TilgangskategoriType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Tilgangsrestriksjon", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class TilgangsrestriksjonType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("TilknyttetRegistreringSom", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class TilknyttetRegistreringSomType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata")]
    [System.Xml.Serialization.XmlRootAttribute("Variantformat", Namespace="http://www.arkivverket.no/standarder/noark5/tj/metadata", IsNullable=false)]
    public partial class VariantformatType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
}
